name: brimo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  lottie: ^1.3.0
  webview_flutter: ^3.0.4
  percent_indicator: ^4.2.2
  qr_code_scanner: ^1.0.0
  flutter_svg: ^1.1.0
  badges: ^2.0.3
  flutter_carousel_widget: ^1.1.0
  introduction_slider: ^1.0.0
  shimmer: ^2.0.0
  get: ^4.6.5
  faker: ^2.0.0
  bottom_sheet: ^3.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
  - assets/
  uses-material-design: true

